[package]
name = "gmock-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
debug = []

[dependencies]
proc-macro2 = {  version = "1.0", features = [ "span-locations" ] }
quote = "1.0"
sha1 = "0.10"
syn = { version = "1.0", features = [ "extra-traits", "full" ] }
