[package]
name = "gmock"
version = "0.1.0"
edition = "2021"

[dependencies]
gmock-macros = "0.1"
once_cell = { version = "1.18", features = [ "parking_lot" ] }
parking_lot = "0.12"
parse_duration = "2.1"

[dev-dependencies]
futures = "0.3"
gmock-macros = { version = "*", features = [ ] }
