check:check:
  stage: check
  image: rust:1.67.1
  variables:
    GIT_CLEAN_FLAGS: -ffdx -e target/
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - .ci/check/check
  tags:
    - rust
  rules:
    - if: '$CI_OPEN_MERGE_REQUESTS && $CI_MERGE_REQUEST_TITLE =~ /^(WIP|wip|Wip|\[Draft\]|\(Draft\)|Draft):/'
      when: manual
    - when: always
