#!/bin/bash

set -e

export PACKAGES=" \
    murf,true,true,true,70.0 \
    murf-macros,true,true,true \
"

export SCRIPT_DIR="$(dirname $0)"
export PROJECT_ROOT="$(readlink -f "$SCRIPT_DIR/../..")"
export COVERAGE_DIR="$PROJECT_ROOT/target/coverage"

"$PROJECT_ROOT/.github/actions/check"
