name: 'Docker Run'
description: 'Run a command in a new container'
inputs:
  image:
    description: 'Image'
    required: true
  user:
    description: 'Run the container as the specified user'
    required: false
  options:
    description: 'Options'
    required: false
  run:
    description: 'Run command in container'
    required: false
  shell:
    description: 'Use a specific shell'
    required: false
    default: sh
  registry:
    description: 'Registry'
    required: false
  username:
    description: 'Username'
    required: false
  password:
    description: 'Password'
    required: false
  docker_network:
    description: 'Docker Network ID'
    default: ${{ job.container.network }}
    required: false
  volumes:
    description: 'Volumes that should be used for the container'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run Docker Container
      shell: bash
      run: ${{ github.action_path }}/exec.sh
      env:
        INPUT_IMAGE: ${{ inputs.image }}
        INPUT_USER: ${{ inputs.user }}
        INPUT_OPTIONS: ${{ inputs.options }}
        INPUT_RUN: ${{ inputs.run }}
        INPUT_SHELL: ${{ inputs.shell }}
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_DOCKER_NETWORK: ${{ inputs.docker_network }}
        INPUT_VOLUMES: ${{ inputs.volumes }}
